/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package clase.pkg5;

import java.awt.event.KeyEvent;
import javax.swing.JTextArea;

/**
 *
 * @author Diego
 */
public class Soportes extends javax.swing.JFrame {

    /**
     * Creates new form Soportes
     */
    public Soportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNro = new javax.swing.JTextField();
        lblAlta = new javax.swing.JTextField();
        lblBaja = new javax.swing.JTextField();
        lblSuscripcion = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        lblCanal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblCorreo = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/me/myimageapp/resources/movileicon.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel2.setText("MSISDN:");

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel3.setText("ALTA:");

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel4.setText("BAJA:");

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel5.setText("Tipo Suscripción:");

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel6.setText("CREADOR MAILS SOPORTE");

        lblNro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblNroKeyPressed(evt);
            }
        });

        lblSuscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblSuscripcionActionPerformed(evt);
            }
        });
        lblSuscripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblSuscripcionKeyPressed(evt);
            }
        });

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        btnCrear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCrearKeyPressed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        jLabel7.setText("Canal (opcional): ");

        lblCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCanalActionPerformed(evt);
            }
        });
        lblCanal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblCanalKeyPressed(evt);
            }
        });

        lblCorreo.setEditable(false);
        lblCorreo.setColumns(20);
        lblCorreo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblCorreo.setRows(5);
        jScrollPane1.setViewportView(lblCorreo);

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 10)); // NOI18N
        jLabel8.setText("(SMS/SIM/WEB/SAT/NRS/NONE)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblBaja, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                            .addComponent(lblAlta)
                                            .addComponent(lblNro))))
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCanal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnLimpiar)))
                .addGap(0, 39, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblNro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblBaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblSuscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblCanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnLimpiar))
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSuscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblSuscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSuscripcionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        lblAlta.setText(null);
        lblBaja.setText(null);
        lblCorreo.setText(null);
        lblNro.setText(null);
        lblSuscripcion.setText(null);
        lblCanal.setText(null);
// TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        if (!(lblSuscripcion.getText().equalsIgnoreCase("SMS")||lblSuscripcion.getText().equalsIgnoreCase("WEB")||lblSuscripcion.getText().equalsIgnoreCase("SAT")||lblSuscripcion.getText().equalsIgnoreCase("NRS")||lblSuscripcion.getText().equalsIgnoreCase("SIM"))) {
            lblCorreo.setText("ERROR EN TIPO SUSCRIPCION, REVISAR!!");
                    }
        if (lblSuscripcion.getText().equalsIgnoreCase("NONE")) {
            lblCorreo.setText("Buenas tardes,\n"
                    + "El usuario con línea "+lblNro.getText()+" no ha tenido suscripciones");
        }
        if (lblSuscripcion.getText().equalsIgnoreCase("SMS")||lblSuscripcion.getText().equalsIgnoreCase("SIM")) {
            lblCorreo.setText("Linea: "+lblNro.getText()+
                    "\nSuscripcion: SMS/SIM"+
                    "\nFecha Alta: "+lblAlta.getText()+
                    "\nFecha Baja: "+lblBaja.getText()+
                    "\n"+
                    "\nEl usuario envia el Mo con la palabra ACEPTAR y le llega el MT: "+
                    "\nBienvenido a “"+lblCanal.getText()+"” recibirás un contenido nuevo diariamente. Para baja enviar BAJA al 35852");
                    }
        if (lblSuscripcion.getText().equalsIgnoreCase("SAT")) {
            lblCorreo.setText("\nLinea: "+lblNro.getText()+
                    "\nSuscripcion: SAT"+
                    "\nFecha Alta: "+lblAlta.getText()+
                    "\nFecha Baja: "+lblBaja.getText()+
                    "\n"+
                    "\nEl usuario realizo la siguiente navegación: Vive tu SIM/ información/ lo último. \nEn esta última categoría teníamos la promoción del canal "+lblCanal.getText()+" (el cual es por SAT), \ndonde el usuario de la línea "+lblNro.getText()+" acepto los términos y condiciones de esta campaña.");
                            }
        if (lblSuscripcion.getText().equalsIgnoreCase("NRS")) {
            lblCorreo.setText("\nLinea: "+lblNro.getText()+
                    "\nSuscripcion: SMS"+
                    "\nFecha Alta: "+lblAlta.getText()+
                    "\nFecha Baja: "+lblBaja.getText()+
                    "\n"+
                    "\nEl usuario recibe un mensaje sugiriendo la suscripción a Elite Latinas, al pulsar el boton recibe el siguiente MT:"+
                    "\n“Bienvenido a Elite Latinas Colombia. Ya puede disfrutar de todos los videos de las chicas mas sexys y glamurosas.”"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\nTERMINOS LEGALES: Los vídeos más atractivos en tu celular. Servicio para mayores de 18 años. \n"
                    + "Pulsando el botón confirmar enviarás un SMS con lapalabra ELITE al 35789 y activarás la suscripción en ELite Latinas. \n"
                    + "Por cada SMS se cobraran diario $600Iva Incluido. Para cancelar envía SALIR al 35789. Net Real Solutions SL. nº at.clte 018000423000,\n"
                    + " Atencion al cliente: clubhola.colombia@movile.com ");
                    
        }
        if (lblSuscripcion.getText().equalsIgnoreCase("WEB")) {
            lblCorreo.setText("\nLinea: "+lblNro.getText()+
                    "\nSuscripcion: WEB"+
                    "\nFecha Alta: "+lblAlta.getText()+
                    "\nFecha Baja: "+lblBaja.getText()+
                    "\n"+
                    "\nMecanica:"+
                    "\nEl usuario ingresa a la Landing Page donde se encuentra descritos los servicios que va a adquirir, ingresa su número celular y le llega un pin el cual debe ingresar para continuar con el proceso. "
                    + "\nLe llega un SMS de bienvenida y  diariamente le llega un contenido. Para realizar el proceso de cancelación el usuario envía BAJA al 35852"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\nCondiciones del Servicio:"+
                    "\n“Para servicio al cliente, escriba un correo electrónico a la dirección clubhola.colombia@movile.com o comuníquese al teléfono 018000423000. \n"
                    + "Su teléfono celular debe tener capacidad para servicios de mensajería de texto. Para recibir los premios de contenidos digitales, su celular debe tener activo el servicio de datos GPRS. \n"
                    + "Para poder usar el servicio, usted tiene que ser el dueño del teléfono celular y tener más de dieciocho años o tener el permiso de sus padres o tutores en caso de ser menor de edad, lo que se podrá requerir en cualquier momento. \n"
                    + "Si usted no cubre estos requisitos, debe enviar BAJA al 34567. Al registrarse para este servicio e ingresar en este sitio el código personal de xxxxx dígitos enviado al número de teléfono móvil indicado por usted (web-opt-in) o \n"
                    + "al enviar el código personal de cuatro números generado por este Sitio al número corto indicado (mobile-opt-in), usted reconoce, acepta y acuerda todos los Términos de Uso. \n"
                    + "Usted puede terminar esta suscripción en cualquier momento enviando un mensaje de texto con la palabra BAJA al código 34567 desde su celular. Usted recibirá un cargo de $600 pesos IVA incluido por cada mensaje recibido, \n"
                    + " serán descontados del saldo de su teléfono móvil en el caso de ser prepago, o incluidos en su próxima factura si es postpago.”");
        }
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCrearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCrearKeyPressed
        
    }//GEN-LAST:event_btnCrearKeyPressed

    private void lblNroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblNroKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
               lblAlta.setText(null);
        lblBaja.setText(null);
        lblCorreo.setText(null);
        lblNro.setText(null);
        lblSuscripcion.setText(null);
        lblCanal.setText(null);
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
        if (!(lblSuscripcion.getText().equalsIgnoreCase("SMS")||lblSuscripcion.getText().equalsIgnoreCase("WEB")||lblSuscripcion.getText().equalsIgnoreCase("SAT")||lblSuscripcion.getText().equalsIgnoreCase("NRS")||lblSuscripcion.getText().equalsIgnoreCase("SIM"))) {
            lblCorreo.setText("ERROR EN TIPO SUSCRIPCION, REVISAR!!");
        }
        if (lblSuscripcion.getText().equalsIgnoreCase("NONE")) {
            lblCorreo.setText("Buenas tardes,\n"
                    + "El usuario con línea "+lblNro.getText()+" no ha tenido suscripciones");
        }
        if (lblSuscripcion.getText().equalsIgnoreCase("SMS")||lblSuscripcion.getText().equalsIgnoreCase("SIM")) {
            lblCorreo.setText("Linea: "+lblNro.getText()+
                    "\nSuscripcion: SMS/SIM"+
                    "\nFecha Alta: "+lblAlta.getText()+
                    "\nFecha Baja: "+lblBaja.getText()+
                    "\n"+
                    "\nEl usuario envia el Mo con la palabra ACEPTAR y le llega el MT: "+
                    "\nBienvenido a “"+lblCanal.getText()+"” recibirás un contenido nuevo diariamente. Para baja enviar BAJA al 35852");
                    }
        if (lblSuscripcion.getText().equalsIgnoreCase("SAT")) {
            lblCorreo.setText("\nLinea: "+lblNro.getText()+
                    "\nSuscripcion: SAT"+
                    "\nFecha Alta: "+lblAlta.getText()+
                    "\nFecha Baja: "+lblBaja.getText()+
                    "\n"+
                    "\nEl usuario realizo la siguiente navegación: Vive tu SIM/ información/ lo último. \nEn esta última categoría teníamos la promoción del canal "+lblCanal.getText()+" (el cual es por SAT), \ndonde el usuario de la línea "+lblNro.getText()+" acepto los términos y condiciones de esta campaña.");
                            }
        if (lblSuscripcion.getText().equalsIgnoreCase("NRS")) {
            lblCorreo.setText("\nLinea: "+lblNro.getText()+
                    "\nSuscripcion: SMS"+
                    "\nFecha Alta: "+lblAlta.getText()+
                    "\nFecha Baja: "+lblBaja.getText()+
                    "\n"+
                    "\nEl usuario recibe un mensaje sugiriendo la suscripción a Elite Latinas, al pulsar el boton recibe el siguiente MT:"+
                    "\n“Bienvenido a Elite Latinas Colombia. Ya puede disfrutar de todos los videos de las chicas mas sexys y glamurosas.”"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\nTERMINOS LEGALES: Los vídeos más atractivos en tu celular. Servicio para mayores de 18 años. \n"
                    + "Pulsando el botón confirmar enviarás un SMS con lapalabra ELITE al 35789 y activarás la suscripción en ELite Latinas. \n"
                    + "Por cada SMS se cobraran diario $600Iva Incluido. Para cancelar envía SALIR al 35789. Net Real Solutions SL. nº at.clte 018000423000,\n"
                    + " Atencion al cliente: clubhola.colombia@movile.com ");
                    
        }
        if (lblSuscripcion.getText().equalsIgnoreCase("WEB")) {
            lblCorreo.setText("\nLinea: "+lblNro.getText()+
                    "\nSuscripcion: WEB"+
                    "\nFecha Alta: "+lblAlta.getText()+
                    "\nFecha Baja: "+lblBaja.getText()+
                    "\n"+
                    "\nMecanica:"+
                    "\nEl usuario ingresa a la Landing Page donde se encuentra descritos los servicios que va a adquirir, ingresa su número celular y le llega un pin el cual debe ingresar para continuar con el proceso. "
                    + "\nLe llega un SMS de bienvenida y  diariamente le llega un contenido. Para realizar el proceso de cancelación el usuario envía BAJA al 35852"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\nCondiciones del Servicio:"+
                    "\n“Para servicio al cliente, escriba un correo electrónico a la dirección clubhola.colombia@movile.com o comuníquese al teléfono 018000423000. \n"
                    + "Su teléfono celular debe tener capacidad para servicios de mensajería de texto. Para recibir los premios de contenidos digitales, su celular debe tener activo el servicio de datos GPRS. \n"
                    + "Para poder usar el servicio, usted tiene que ser el dueño del teléfono celular y tener más de dieciocho años o tener el permiso de sus padres o tutores en caso de ser menor de edad, lo que se podrá requerir en cualquier momento. \n"
                    + "Si usted no cubre estos requisitos, debe enviar BAJA al 34567. Al registrarse para este servicio e ingresar en este sitio el código personal de xxxxx dígitos enviado al número de teléfono móvil indicado por usted (web-opt-in) o \n"
                    + "al enviar el código personal de cuatro números generado por este Sitio al número corto indicado (mobile-opt-in), usted reconoce, acepta y acuerda todos los Términos de Uso. \n"
                    + "Usted puede terminar esta suscripción en cualquier momento enviando un mensaje de texto con la palabra BAJA al código 34567 desde su celular. Usted recibirá un cargo de $600 pesos IVA incluido por cada mensaje recibido, \n"
                    + " serán descontados del saldo de su teléfono móvil en el caso de ser prepago, o incluidos en su próxima factura si es postpago.”");
        }      
}        // TODO add your handling code here:
    }//GEN-LAST:event_lblNroKeyPressed

    private void lblSuscripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblSuscripcionKeyPressed
          if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
               lblAlta.setText(null);
        lblBaja.setText(null);
        lblCorreo.setText(null);
        lblNro.setText(null);
        lblSuscripcion.setText(null);
        lblCanal.setText(null);
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
        if (!(lblSuscripcion.getText().equalsIgnoreCase("SMS")||lblSuscripcion.getText().equalsIgnoreCase("WEB")||lblSuscripcion.getText().equalsIgnoreCase("SAT")||lblSuscripcion.getText().equalsIgnoreCase("NRS")||lblSuscripcion.getText().equalsIgnoreCase("SIM"))) {
            lblCorreo.setText("ERROR EN TIPO SUSCRIPCION, REVISAR!!");
        }
        if (lblSuscripcion.getText().equalsIgnoreCase("NONE")) {
            lblCorreo.setText("Buenas tardes,\n"
                    + "El usuario con línea "+lblNro.getText()+" no ha tenido suscripciones");
        }
        if (lblSuscripcion.getText().equalsIgnoreCase("SMS")||lblSuscripcion.getText().equalsIgnoreCase("SIM")) {
            lblCorreo.setText("Linea: "+lblNro.getText()+
                    "\nSuscripcion: SMS/SIM"+
                    "\nFecha Alta: "+lblAlta.getText()+
                    "\nFecha Baja: "+lblBaja.getText()+
                    "\n"+
                    "\nEl usuario envia el Mo con la palabra ACEPTAR y le llega el MT: "+
                    "\nBienvenido a “"+lblCanal.getText()+"” recibirás un contenido nuevo diariamente. Para baja enviar BAJA al 35852");
                    }
        if (lblSuscripcion.getText().equalsIgnoreCase("SAT")) {
            lblCorreo.setText("\nLinea: "+lblNro.getText()+
                    "\nSuscripcion: SAT"+
                    "\nFecha Alta: "+lblAlta.getText()+
                    "\nFecha Baja: "+lblBaja.getText()+
                    "\n"+
                    "\nEl usuario realizo la siguiente navegación: Vive tu SIM/ información/ lo último. \nEn esta última categoría teníamos la promoción del canal "+lblCanal.getText()+" (el cual es por SAT), \ndonde el usuario de la línea "+lblNro.getText()+" acepto los términos y condiciones de esta campaña.");
                            }
        if (lblSuscripcion.getText().equalsIgnoreCase("NRS")) {
            lblCorreo.setText("\nLinea: "+lblNro.getText()+
                    "\nSuscripcion: SMS"+
                    "\nFecha Alta: "+lblAlta.getText()+
                    "\nFecha Baja: "+lblBaja.getText()+
                    "\n"+
                    "\nEl usuario recibe un mensaje sugiriendo la suscripción a Elite Latinas, al pulsar el boton recibe el siguiente MT:"+
                    "\n“Bienvenido a Elite Latinas Colombia. Ya puede disfrutar de todos los videos de las chicas mas sexys y glamurosas.”"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\nTERMINOS LEGALES: Los vídeos más atractivos en tu celular. Servicio para mayores de 18 años. \n"
                    + "Pulsando el botón confirmar enviarás un SMS con lapalabra ELITE al 35789 y activarás la suscripción en ELite Latinas. \n"
                    + "Por cada SMS se cobraran diario $600Iva Incluido. Para cancelar envía SALIR al 35789. Net Real Solutions SL. nº at.clte 018000423000,\n"
                    + " Atencion al cliente: clubhola.colombia@movile.com ");
                    
        }
        if (lblSuscripcion.getText().equalsIgnoreCase("WEB")) {
            lblCorreo.setText("\nLinea: "+lblNro.getText()+
                    "\nSuscripcion: WEB"+
                    "\nFecha Alta: "+lblAlta.getText()+
                    "\nFecha Baja: "+lblBaja.getText()+
                    "\n"+
                    "\nMecanica:"+
                    "\nEl usuario ingresa a la Landing Page donde se encuentra descritos los servicios que va a adquirir, ingresa su número celular y le llega un pin el cual debe ingresar para continuar con el proceso. "
                    + "\nLe llega un SMS de bienvenida y  diariamente le llega un contenido. Para realizar el proceso de cancelación el usuario envía BAJA al 35852"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\nCondiciones del Servicio:"+
                    "\n“Para servicio al cliente, escriba un correo electrónico a la dirección clubhola.colombia@movile.com o comuníquese al teléfono 018000423000. \n"
                    + "Su teléfono celular debe tener capacidad para servicios de mensajería de texto. Para recibir los premios de contenidos digitales, su celular debe tener activo el servicio de datos GPRS. \n"
                    + "Para poder usar el servicio, usted tiene que ser el dueño del teléfono celular y tener más de dieciocho años o tener el permiso de sus padres o tutores en caso de ser menor de edad, lo que se podrá requerir en cualquier momento. \n"
                    + "Si usted no cubre estos requisitos, debe enviar BAJA al 34567. Al registrarse para este servicio e ingresar en este sitio el código personal de xxxxx dígitos enviado al número de teléfono móvil indicado por usted (web-opt-in) o \n"
                    + "al enviar el código personal de cuatro números generado por este Sitio al número corto indicado (mobile-opt-in), usted reconoce, acepta y acuerda todos los Términos de Uso. \n"
                    + "Usted puede terminar esta suscripción en cualquier momento enviando un mensaje de texto con la palabra BAJA al código 34567 desde su celular. Usted recibirá un cargo de $600 pesos IVA incluido por cada mensaje recibido, \n"
                    + " serán descontados del saldo de su teléfono móvil en el caso de ser prepago, o incluidos en su próxima factura si es postpago.”");
        }      
}    // TODO add your handling code here:
    }//GEN-LAST:event_lblSuscripcionKeyPressed

    private void lblCanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCanalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCanalActionPerformed

    private void lblCanalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblCanalKeyPressed
 if (evt.getKeyCode()==KeyEvent.VK_ESCAPE) {
               lblAlta.setText(null);
        lblBaja.setText(null);
        lblCorreo.setText(null);
        lblNro.setText(null);
        lblSuscripcion.setText(null);
        lblCanal.setText(null);
        }
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
        if (!(lblSuscripcion.getText().equalsIgnoreCase("SMS")||lblSuscripcion.getText().equalsIgnoreCase("WEB")||lblSuscripcion.getText().equalsIgnoreCase("SAT")||lblSuscripcion.getText().equalsIgnoreCase("NRS")||lblSuscripcion.getText().equalsIgnoreCase("SIM"))) {
            lblCorreo.setText("ERROR EN TIPO SUSCRIPCION, REVISAR!!");
        }
        
        if (lblSuscripcion.getText().equalsIgnoreCase("NONE")) {
            lblCorreo.setText("Buenas tardes,\n"
                    + "El usuario con línea "+lblNro.getText()+" no ha tenido suscripciones");
        }
        if (lblSuscripcion.getText().equalsIgnoreCase("SMS")||lblSuscripcion.getText().equalsIgnoreCase("SIM")) {
            lblCorreo.setText("Linea: "+lblNro.getText()+
                    "\nSuscripcion: SMS/SIM"+
                    "\nFecha Alta: "+lblAlta.getText()+
                    "\nFecha Baja: "+lblBaja.getText()+
                    "\n"+
                    "\nEl usuario envia el Mo con la palabra ACEPTAR y le llega el MT: "+
                    "\n“Bienvenido a “"+lblCanal.getText()+"” recibirás un contenido nuevo diariamente. Para baja enviar BAJA al 35852”");
                    }
        if (lblSuscripcion.getText().equalsIgnoreCase("SAT")) {
            lblCorreo.setText("\nLinea: "+lblNro.getText()+
                    "\nSuscripcion: SAT"+
                    "\nFecha Alta: "+lblAlta.getText()+
                    "\nFecha Baja: "+lblBaja.getText()+
                    "\n"+
                    "\nEl usuario realizo la siguiente navegación: Vive tu SIM/ información/ lo último. \nEn esta última categoría teníamos la promoción del canal "+lblCanal.getText()+" (el cual es por SAT), \ndonde el usuario de la línea "+lblNro.getText()+" acepto los términos y condiciones de esta campaña.");
                            }
        if (lblSuscripcion.getText().equalsIgnoreCase("NRS")) {
            lblCorreo.setText("\nLinea: "+lblNro.getText()+
                    "\nSuscripcion: SMS"+
                    "\nFecha Alta: "+lblAlta.getText()+
                    "\nFecha Baja: "+lblBaja.getText()+
                    "\n"+
                    "\nEl usuario recibe un mensaje sugiriendo la suscripción a Elite Latinas, al pulsar el boton recibe el siguiente MT:"+
                    "\n“Bienvenido a Elite Latinas Colombia. Ya puede disfrutar de todos los videos de las chicas mas sexys y glamurosas.”"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\nTERMINOS LEGALES: Los vídeos más atractivos en tu celular. Servicio para mayores de 18 años. \n"
                    + "Pulsando el botón confirmar enviarás un SMS con lapalabra ELITE al 35789 y activarás la suscripción en ELite Latinas. \n"
                    + "Por cada SMS se cobraran diario $600Iva Incluido. Para cancelar envía SALIR al 35789. Net Real Solutions SL. nº at.clte 018000423000,\n"
                    + " Atencion al cliente: clubhola.colombia@movile.com ");
                    
        }
        if (lblSuscripcion.getText().equalsIgnoreCase("WEB")) {
            lblCorreo.setText("\nLinea: "+lblNro.getText()+
                    "\nSuscripcion: WEB"+
                    "\nFecha Alta: "+lblAlta.getText()+
                    "\nFecha Baja: "+lblBaja.getText()+
                    "\n"+
                    "\nMecanica:"+
                    "\nEl usuario ingresa a la Landing Page donde se encuentra descritos los servicios que va a adquirir, ingresa su número celular y le llega un pin el cual debe ingresar para continuar con el proceso. "
                    + "\nLe llega un SMS de bienvenida y  diariamente le llega un contenido. Para realizar el proceso de cancelación el usuario envía BAJA al 35852"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\n"+
                    "\nCondiciones del Servicio:"+
                    "\n“Para servicio al cliente, escriba un correo electrónico a la dirección clubhola.colombia@movile.com o comuníquese al teléfono 018000423000. \n"
                    + "Su teléfono celular debe tener capacidad para servicios de mensajería de texto. Para recibir los premios de contenidos digitales, su celular debe tener activo el servicio de datos GPRS. \n"
                    + "Para poder usar el servicio, usted tiene que ser el dueño del teléfono celular y tener más de dieciocho años o tener el permiso de sus padres o tutores en caso de ser menor de edad, lo que se podrá requerir en cualquier momento. \n"
                    + "Si usted no cubre estos requisitos, debe enviar BAJA al 34567. Al registrarse para este servicio e ingresar en este sitio el código personal de xxxxx dígitos enviado al número de teléfono móvil indicado por usted (web-opt-in) o \n"
                    + "al enviar el código personal de cuatro números generado por este Sitio al número corto indicado (mobile-opt-in), usted reconoce, acepta y acuerda todos los Términos de Uso. \n"
                    + "Usted puede terminar esta suscripción en cualquier momento enviando un mensaje de texto con la palabra BAJA al código 34567 desde su celular. Usted recibirá un cargo de $600 pesos IVA incluido por cada mensaje recibido, \n"
                    + " serán descontados del saldo de su teléfono móvil en el caso de ser prepago, o incluidos en su próxima factura si es postpago.”");
        }      
}         // TODO add your handling code here:
    }//GEN-LAST:event_lblCanalKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lblAlta;
    private javax.swing.JTextField lblBaja;
    private javax.swing.JTextField lblCanal;
    private javax.swing.JTextArea lblCorreo;
    private javax.swing.JTextField lblNro;
    private javax.swing.JTextField lblSuscripcion;
    // End of variables declaration//GEN-END:variables
}
